### ISSUE TITLE
Migration from domain to AHD

### ISSUE THREAD

**Issue by ORESoftware** [tapjs/async-hook-domain#23]
Need some insight as to why my migration from core domain to AHD is hiccupy.

I have this project, just middleware that attaches an original domain to each request:
https://github.com/ORESoftware/domain-haven

It works really really well, but it does cause about 25% perf cost to a Node server under load.

It basically does this (not this simple, but this is the gist):

```typescript
const domain = require('domain');

app.use((req, res, next) => {

   const d  = domain.create();

   res.once('finish', () => {
      d.dispose();
   });

   d.once(' error', err => {
        res.status(500).json(err);
   });

   d.run(next);
});
```

I notice that AHD is more performant, however, and I would like to convert my code, but if I change my code to this:

```typescript
const ahd = require('async-hook-domain');

app.use((req, res, next) => {

   const d  =  new ahd.Domain(err => {
      res.status(500).json(err);                  
  });
  
   res.once('finish', () => {
          d.destroy();
   });

   next();

});
```

Not sure if my AHD code is correct, but it hiccups and falters more than my original code. Eventually I will get a timeout.
Would be happy to show the code I use, it's a server that takes 50K requests about 200 at a time.

**Comment by ORESoftware** [comment]
I did basic analysis and in my best estimation, it's not capturing all async errors thrown - would be happy to demo, since I am very confident either there is a problem with the lib or I am using the lib incorrectly - if the latter - then we should update the docs to show how to use a for an express server etc.

**Comment by ORESoftware** [comment]
this was a Node 14 vs Node 20 issue, works (mostly*) as expected on version 20
the only problem I noticed was when I had my own process.on('unhandledRejection') and process.on('uncaughtException'), then I had an issue

**Comment by Damaged-Organic** [comment]
Hi @ORESoftware. I've found this package in a reference from your article, so , first of all, thank you : ) I've tried to use the it and had an issue with having `unhandledRejection` and `uncaughtException` listeners to work as a root level interceptors (I believe the same as you did). When those listeners are installed, AHD listeners are completely bypassed, which is a showstopper. Were you able to find solution to this?

P.S.: tagging @isaacs just in case, see there's not a lot of responses from the author here.

**Comment by isaacs** [comment]
@Damaged-Organic In the future, please create new issues for new issues, rather than posting your new problem as a comment on an old issue. Otherwise, it's far more likely (in some cases, nearly guaranteed) that your problem will be overlooked, and even if it isn't, the solution will not be searchable by future users, and it will likely spam a bunch of other people who can't help you anyway.

AHD intentionally does not trigger the Domain error handler if you have a `process.on('uncaughtException')` handler, because it's only intended to handle cases that would crash the process.  If you have your own handler that handles the error, then the error won't crash the process, so the domain should not trigger.
