### ISSUE TITLE
Returning `true` for process emit changes behavior and negatively impacts `when` library

### ISSUE THREAD

**Issue by michaelgoin** [tapjs/async-hook-domain#3]
Ran into this attempting to upgrade `tap` versions.

This library wraps process emit. In the domain case, it does a `|| true` on emit potentially indicating it emitted to a handler when it did not.

https://github.com/isaacs/async-hook-domain/blob/master/index.js#L134

Unfortunately, `when` relies on knowing if that was emitted or not before invoking its own handler.

https://github.com/cujojs/when/blob/master/lib/makePromise.js#L654

This breaks one of our tests where we are verifying we didn't in-fact change behaviors. 

I'm guessing the `true` is there for some edge case but wanted to surface up the potential behavior change there.

----

Guessing this spot could cause problems, as well: https://github.com/isaacs/async-hook-domain/blob/master/index.js#L123

**Comment by isaacs** [comment]
Hm, that's a tricky one.  It's not really an edge case, it's kind of core to what this module does.

The domain returns true because otherwise the process will crash, and the whole point is to _not_ have the process crash in that case, because the domain handled the error.  Essentially, this is a conditional `process.on('uncaughtException')` listener -- if there are no other handlers, then we need to ensure that the domain handler is treated as if it did handle the event.  But in the case that we _don't_ handle the error, we need to let node know that it wasn't handled (unless someone else handles it, of course).

So, essentially, it _did_ emit to a handler in that case, which did handle the error.

The only other way to do that would be to _not_ emit the event at all, but that of course causes even bigger problems and will throw off other error handling logic like `when`, I'd imagine.

A potential way forward would be an API to tell tap not to use async-hook-domain handling for its errors, but of course _that_ means that thrown errors in tests will just blow all the way up.  Would that be helpful to you?

**Comment by michaelgoin** [comment]
@isaacs sorry for the very late reply.

I do believe that API may be helpful. In our case, we are trying to verify we do not change error behaviors based on our code. Since the test framework changes those behaviors (on purpose) it throws off our testing. Right now, I'm basically monkey-patching to prevent that.

```js
temporarilyOverrideTapUncaughtBehavior: (tap, t) => {
    const originalThrew = tap.threw
    // Prevent tap from failing test and remove extra prop
    tap.threw = (err) => {
      delete err.tapCaught
    }

    const originalTestThrew = t.threw
    t.threw = (err) => {
      delete err.tapCaught
    }

    t.teardown(() => {
      t.threw = originalTestThrew
      tap.threw = originalThrew
    })
  },
```

May be worth noting, our tests typically (i guess not always) have a handler for `uncaughtException` exception in the test that would prevent the crash, but this prevents that from handling normally.

**Comment by isaacs** [comment]
> @isaacs sorry for the very late reply.

hold my beer 😅

Would `tap.expectUncaughtException` be useful here in some way?

Tbh, the monkeypatch doesn't strike me as too terrible.  `when` lives in that same weird realm of error management that tap and async-hook-domain live, so these kinds of hacks are sort of just what you do sometimes.  I'm sure it could certainly have been made more clear how to go about doing that, and I'll leave this open as a docs task.  But I think having a hacky workaround in one project is probably better than _not_ catching errors in general in a test runner, for most cases that would prefer to have them handled nicely.

I will also add an opt-out switch for ahd in tap v18, but probably will not backport it to earlier versions, since it's threaded through so many places, it'd be risky to try it without the kind of rewrite that v18 will be anyway.

**Comment by isaacs** [comment]
This should actually not be a problem on v3.  Will publish to npm once I can figure out why CI isn't running.
